### ISSUE TITLE
[Bug] - Game crashes when taking screenshot in menu

### ISSUE THREAD

**Issue by ComradeBlaze** [Loedje/screenshot_organisation#1]
Title summarizes the issue.

To reproduce, go into the title menu or options menu and hit F2 to screenshot. Game crashes. 
Attached is a crash log. 

https://mclo.gs/2VGxnTf

Note: the screenshot does get taken, and is saved to the root screenshot directory. Possibly a categorization error?

Thanks.

**Comment by Loedje** [comment]
Thank! I fixed it, new version is available for download.
