### ISSUE TITLE
[Suggestion] Automatic folder generation

### ISSUE THREAD

**Issue by PencilVoid** [Loedje/screenshot_organisation#2]
At the moment it seems folders have to be assigned to worlds or servers manually. It would be nice if the mod could automatically generate folders for each world or server based on the name.

**Comment by Loedje** [comment]
It should already be doing this. These folders are placed in the screenshots directory of your Minecraft directory.

If I make a new world, take a screenshot, click on the screenshot in the chat, right click the image and click Open in File Explorer it goes to the automatically created folder which matches the world name. Could you test out if this works for you as well? Should work the same for servers. I use Windows so maybe it works differently on other systems.

Let me know if you still encounter problems or have any other suggestions!

**Comment by PencilVoid** [comment]
It seems to function the same as it would without the mod (i.e. screenshots are put in the default screenshot folder). Might be a compatibility issue with the mod [Shared Resources](https://github.com/enjarai/shared-resources).

**Comment by Loedje** [comment]
Hey, I just uploaded a [new version](https://modrinth.com/mod/screenshot-organisation/versions) that should now be compatible with Shared Resources.
