### ISSUE TITLE
Game crashing while trying to take a screenshot

### ISSUE THREAD

**Issue by 21Charles** [Loedje/screenshot_organisation#3]
i installed this mod and didn't change anything, when i tried to click F2, the game crashed, here's: the crash report:
[crash-2024-06-27_13.45.52-client.txt](https://github.com/user-attachments/files/16012866/crash-2024-06-27_13.45.52-client.txt)

**Comment by Loedje** [comment]
thank you, should be fixed now in new version, let me know if you encounter any further problems

**Comment by Loedje** [comment]
i think i uploaded the wrong version to modrinth just now, but i think it is fixed now

**Comment by 21Charles** [comment]
thank you so much
